#!/bin/bash
# File              : dmenu_bootable
# License           : MIT License
# Author            : M. Nabil Adani <macroid48@gmail.com>
# Date              : Minggu, 27/10/2019 09:28 WIB
# Last Modified Date: Rabu, 06/11/2019 15:41 WIB
# Last Modified By  : M. Nabil Adani <macroid48@gmail.com>


DMENU='dmenu -x 300 -y 220 -w 800 -fn Iosevka-11 -l 5 -i'
choice=$(echo -e "File Iso\nFlashDrive" | $DMENU -p Bootable)

function file_iso(){
  file=$(find /mnt/Data/Sistem\ Operasi -iname '*.iso'|$DMENU -p Iso\ File)
  if [[ -f $file ]] ; then
    ram=$(echo -e "64\n128\n512\n1024\n2024" | $DMENU -p Ram\ Size)
    if [[ ! -z $ram ]]; then
      qemu-system-x86_64 -enable-kvm -boot d -m $ram -cdrom "$file"
    fi
  fi
}
function flash_drive(){
  fd=$(udiskie-info -C -2 -a -o '{ui_label}' | $DMENU | cut -d ":" -f 1)
  ram=$(echo -e "64\n128\n512\n1024\n2024" | $DMENU -p Ram\ Size)
  if [[ ! -z $ram ]]; then
    sudo qemu-system-x86_64 -enable-kvm -m $ram -vga std -hda "$fd" 
  fi
}
case "$choice" in
  "File Iso") file_iso;;
  "FlashDrive") flash_drive;;
esac
